EnglishExpert/urls.py
from django.urls import path, include

urlpatterns = [
    path("", include("deect.urls", namespace="words")),
    path("", include("search.urls", namespace="search")),
]

deect/urls.py
from django.conf.urls import url

from deect.views import words, en_translation, pl_translation, en_random, pl_random

app_name = "deect"

urlpatterns = [
    url(r"^words/$", words, name="words"),
    url(r"^words/en/(?P<word>[\w-]+)/$", en_translation, name="en_translation"),
    url(r"^words/pl/(?P<word>[\w-]+)/$", pl_translation, name="pl_translation"),
    url(r"^words/random/en/$", en_random, name="en_random"),
    url(r"^words/random/pl/$", pl_random, name="pl_random"),

    # url(r"^product/(?P<product_id>[0-9]+)/$", product_details, name="product_details"),
]
# if settings.DEBUG:
#     urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.conf.urls import url

from search.views import search

app_name = "search "

urlpatterns = [
    url(r"^search/", search, name="searcch"),
]
# if settings.DEBUG:
#     urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

deect/models.py
from datetime import datetime

import django
from django.db import models


class Word(models.Model):
    word = models.CharField(max_length=255,)
    translation = models.CharField(max_length=255)
    date = models.DateField(default=django.utils.timezone.now)
    tutor = models.CharField(max_length=255, null=True)
    category = models.CharField(max_length=255, null=True)

search/models.py
from django.db import models

# Create your models here.

deect/views.py
import random

from django.shortcuts import render

from .models import Word


def words(request):

    words = Word.objects.all()
    return render(request, "words.html", {"words": words})


def en_translation(request, word):
    word = Word.objects.get(word=word)
    return render(request, "words.html", {"word": word.translation})


def pl_translation(request, word):
    word = Word.objects.get(translation=word)
    return render(request, "words.html", {"word": word.word})


def pl_random(request):
    ids = Word.objects.values_list("id", flat=True)
    id = random.choice(ids)
    word = Word.objects.get(id=id)
    return render(
        request, "words.html", {"word": word.translation, "translation": word.word}
    )


def en_random(request):
    ids = Word.objects.values_list("id", flat=True)
    id = random.choice(ids)
    word = Word.objects.get(id=id)

    return render(
        request, "words.html", {"word": word.word, "translation": word.translation}
    )

search/views.py
from django.shortcuts import render

from search.document import WordDocument


def search(request):
    q = request.GET.get('q')
    if q:
        words = WordDocument.search().query("match", word="fri")
    else:
        words = ""

    return render(request, "words.html", {"words": words})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"> </script>
    <title>DEECT</title>
</head>
<body>
   <nav class="navbar navbar-inverse">
        <div class="conteiner-fluid">
             <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
             <div class="collapse navbar-collapse"  id="topNavBar">
                <ul class="nav navbar-nav">
{#                    <li class="dropdown">#}
{#                        <a href="{% url 'deect:words' %}"> Quiz </a>#}
{#                    </li>#}
                    <li class="dropdown">
                        <a href="{% url 'words:pl_random' %}"> RandomPL </a>
                    </li>
                    <li class="dropdown">
                        <a href="{% url 'words:en_random' %}"> RandomEn </a>
                    </li>
                </ul>
             </div>
        </div>
        </div>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/words.html
{% extends 'base.html' %}

{%  block body %}
    <form method="get">

        <input id="q" name="q" type="text" placeholder="szukaj">

    </form>


    {% for word in words %}
        <tr>
            <td>{{ word.word }}  {{ word.translation }}</td>
        </tr>
    {% endfor %}
{% endblock %}